### ISSUE TITLE
Crash with AssertionError

### ISSUE THREAD

**Issue by AronVanAmmers** [OutlierVentures/H2O#4]
Received the error below once. This was after pressing Replicate - but can't be 100% sure that's what caused it. After this, H2O wasn't reachable anymore, I had to restart to make it work again.

```
h2o_1  | webpack: Compiled successfully.
h2o_1  | assert.js:42
h2o_1  |   throw new errors.AssertionError({
h2o_1  |   ^
h2o_1  |
h2o_1  | AssertionError [ERR_ASSERTION]: false == true
h2o_1  |     at PriorityNode.removeChild (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/priority.js:74:3)
h2o_1  |     at PriorityNode.remove (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/priority.js:62:15)
h2o_1  |     at PriorityTree.add (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/priority.js:163:23)
h2o_1  |     at Stream._initPriority (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/stream.js:101:25)
h2o_1  |     at new Stream (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/stream.js:76:8)
h2o_1  |     at Connection._createStream (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:388:16)
h2o_1  |     at Connection._handleHeaders (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:436:21)
h2o_1  |     at Connection._handleFrame (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:319:10)
h2o_1  |     at Parser.<anonymous> (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:156:10)
h2o_1  |     at emitOne (events.js:116:13)
h2o_1  |     at Parser.emit (events.js:211:7)
h2o_1  |     at addChunk (/app/h2o/frontend/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:284:12)
h2o_1  |     at readableAddChunk (/app/h2o/frontend/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:271:11)
h2o_1  |     at Parser.Readable.push (/app/h2o/frontend/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:238:10)
h2o_1  |     at Parser.Transform.push (/app/h2o/frontend/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_transform.js:146:32)
h2o_1  |     at next (/app/h2o/frontend/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:53:12)
h2o_1  | error Command failed with exit code 1.
h2o_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by AronVanAmmers** [comment]
This was in an early version, not seen anymore.
